openapi: 3.0.1
info:
  title: Banking API
  description: API for managing bank accounts and transactions
  version: 1.0.0
  contact:
    email: zahidtaqiyuddinahmad@gmail.com
servers:
  - url: http://localhost:3000/v1
paths:
  /accounts:
    post:
      summary: create a new bank account
      description: createdreates a new bank account for a user.
      requestBody:
        $ref: "#/components/requestBodies/CreateAccount"
      responses:
        201:
          description: account successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BankAccount"
        400:
          description: validation error or user not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - bearerAuth: []

    get:
      summary: list all bank accounts
      description: retrieves a list of all bank accounts.
      responses:
        200:
          description: list of bank accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BankAccount"

  /accounts/{account_id}:
    parameters:
      - name: account_id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: get details of a bank account
      description: retrieves detailed information about a specific bank account.
      responses:
        200:
          description: bank account details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BankAccount"
        404:
          description: account not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /transactions:
    post:
      summary: create a transaction
      description: creates a new transaction between two accounts.
      requestBody:
        $ref: "#/components/requestBodies/CreateTransaction"
      responses:
        201:
          description: transaction successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
        400:
          description: insufficient funds or account not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    BankAccount:
      type: object
      properties:
        id:
          type: integer
          example: 1
        user_id:
          type: integer
          example: 1
        bank_name:
          type: string
          example: "Bank IBN"
        bank_account_number:
          type: string
          example: "1234567890"
        balance:
          type: number
          format: double
          example: 1500000

    Transaction:
      type: object
      properties:
        id:
          type: integer
          example: 1
        sender_account_id:
          type: integer
          example: 1
        receiver_account_id:
          type: integer
          example: 2
        amount:
          type: number
          format: double
          example: 2000000

    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: "validation error or user not found"

  requestBodies:
    CreateAccount:
      content:
        application/json:
          schema:
            type: object
            properties:
              user_id:
                type: integer
                example: 2
              bank_name:
                type: string
                example: "Bank ABC"
              bank_account_number:
                type: string
                example: "1234567890"
              balance:
                type: number
                format: double
                example: 200000

    CreateTransaction:
      content:
        application/json:
          schema:
            type: object
            properties:
              sender_account_id:
                type: integer
                example: 1
              receiver_account_id:
                type: integer
                example: 2
              amount:
                type: number
                format: double
                example: 150000
